### ISSUE TITLE
Idea: Use of proxy

### ISSUE THREAD

**Issue by holtwick** [antfu/birpc#1]
What a genius yet simple implementation! I tried to implement something similar a while ago, but when I look at your solution it seems overcomplicated ;)

Anyway, I use a simple Proxy that allows to use natural functions, e.g. instead of `await bob.call('hi', 'alice)` you could use `await bob.hi('alice')`. Type checks also work well.

You'll find a short description here: https://github.com/holtwick/zeed/tree/master/src/common/msg#messages

And the essential implementation here: https://github.com/holtwick/zeed/blob/master/src/common/msg/messages.ts#L49

**Comment by antfu** [comment]
I thought about it, but initially, I was thinking to have two different ways of calling functions (with/without return). Thanks for bringing this up, and I think I have found a not bad solution to that :)

**Comment by holtwick** [comment]
Indeed, `.noReply` is a very smart solution :) Thanks!

**Comment by holtwick** [comment]
> Indeed, `.noReply` is a very smart solution :) Thanks!

Ah, you modified it again, even better this way.
