### ISSUE TITLE
Support trapping `hasOwnProperty`, `toJSON`, or add denylist of functions

### ISSUE THREAD

**Issue by aulneau** [antfu/birpc#5]
### Clear and concise description of the problem

I'm working on a library that uses the react-native webview and using birpc to pass messages between the webview and main react-native app, to make use of JS features available in the webview, but might not be available in hermes. 

It seems that the RN app is trying to access `hasOwnProperty`, but it's not being handled correctly by birpc. 

```
 WARN  Possible Unhandled Promise Rejection (id: 4):
Error: [birpc] timeout on calling "hasOwnProperty"
```

Additionally, it tries to use `toJSON`:
```
 WARN  Possible Unhandled Promise Rejection (id: 2):
Error: [birpc] timeout on calling "toJSON"
```

If it's not possible to pass these along, maybe a denylist of functions could be added to ignore certain functions from being called on the proxy?

### Suggested solution

https://stackoverflow.com/questions/40451694/use-es6-proxy-to-trap-object-hasownproperty

Seems like it's possible to trap it -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/getOwnPropertyDescriptor

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
At a high level, `birpc` only manages to pass the data. For such case, I suggest to provide your own serialize/deserialize implementation to fit your needs. Thanks
